package skillfood3;

/**
 *
 * @author .
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

public class RunnerFrame extends JFrame implements ActionListener {

        /**
         * Creates new form MainFrame
         */
        private JButton BtnCalculate;
        private JButton BtnClear;
        private JButton ButtonExit;
        private JTextField FieldBrat;
        private JTextField FieldDog;
        private JTextField FieldFries;
        private JTextField FieldHam;
        private JTextField FieldRes;
        private JTextField FieldSoda;
        private JLabel LabelBrat;
        private JLabel LabelBrat2;
        private JLabel LabelDog;
        private JLabel LabelDog2;
        private JLabel LabelFries;
        private JLabel LabelFries2;
        private JLabel LabelHam;
        private JLabel LabelHam2;
        private JLabel LabelSoda;
        private JLabel LabelSoda2;
        private JLabel LabelWater;
        private JLabel LabelWater2;
        private JPanel MainPanel;
        private JTextField WaterField;

        public RunnerFrame() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
        private void initComponents() {
                java.awt.GridBagConstraints gridBagConstraints;

                MainPanel = new JPanel();
                LabelDog = new JLabel("Hot Dog:");
                LabelBrat = new JLabel("Brat:");
                LabelHam = new JLabel("Ham:");
                LabelFries = new JLabel("Fries:");
                LabelSoda = new JLabel("Soda:");
                LabelWater = new JLabel("Water:");
                LabelDog2 = new JLabel("x $2.50");
                LabelBrat2 = new JLabel("x $3.50");
                LabelHam2 = new JLabel("x $5.00");
                LabelFries2 = new JLabel("x $2.00");
                FieldDog = new javax.swing.JTextField();
                FieldBrat = new javax.swing.JTextField();
                FieldHam = new javax.swing.JTextField();
                FieldFries = new javax.swing.JTextField();
                FieldSoda = new javax.swing.JTextField();
                WaterField = new javax.swing.JTextField();
                LabelSoda2 = new JLabel("x $2.00");
                LabelWater2 = new JLabel("Free");
                BtnCalculate = new javax.swing.JButton();
                BtnClear = new javax.swing.JButton();
                FieldRes = new javax.swing.JTextField();
                ButtonExit = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                MainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calculator", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
                MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                MainPanel.add(LabelDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 50, 20));

                MainPanel.add(LabelBrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 50, 20));

                MainPanel.add(LabelHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 20));

                MainPanel.add(LabelFries, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 20));

                MainPanel.add(LabelSoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));

                MainPanel.add(LabelWater, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 60, 20));

                MainPanel.add(LabelDog2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, 20));

                MainPanel.add(LabelBrat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, 20));

                MainPanel.add(LabelHam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, 20));

                MainPanel.add(LabelFries2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, 20));

                FieldDog.setText("0");
                MainPanel.add(FieldDog, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 120, -1));

                FieldBrat.setText("0");
                MainPanel.add(FieldBrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 120, -1));

                FieldHam.setText("0");
                MainPanel.add(FieldHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 120, -1));

                FieldFries.setText("0");
                MainPanel.add(FieldFries, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 120, -1));

                FieldSoda.setText("0");
                MainPanel.add(FieldSoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 120, -1));

                WaterField.setText("0");
                MainPanel.add(WaterField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 120, -1));

                MainPanel.add(LabelSoda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, 20));

                LabelWater2.setText("Free");
                MainPanel.add(LabelWater2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, 20));

                BtnCalculate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                BtnCalculate.setText("Calculate");
                BtnCalculate.addActionListener(this);
                MainPanel.add(BtnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 80, 40));

                BtnClear.setText("Clear");
                BtnClear.addActionListener(this);
                MainPanel.add(BtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 80, 40));

                FieldRes.setEditable(false);
                FieldRes.setText("0");
                MainPanel.add(FieldRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 120, 40));

                getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 320));

                ButtonExit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
                ButtonExit.setText("Exit");
                ButtonExit.addActionListener(this);
                getContentPane().add(ButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 333, 80, 40));

                pack();
        }

        @Override
        public void actionPerformed(ActionEvent e) {
                JButton BtnClicked = (JButton) e.getSource();
                if (BtnClicked == BtnCalculate)
                        BtnCalculateActionPerformed(e);
                else if (BtnClicked == BtnClear)
                        BtnClearActionPerformed(e);
                else if (BtnClicked == ButtonExit)
                        ButtonExitActionPerformed(e);
        }

        private void BtnCalculateActionPerformed(java.awt.event.ActionEvent evt) {

                FieldRes.setText("0");
                JTextField[] Jarr = new JTextField[]{FieldDog, FieldBrat, FieldHam, FieldFries, FieldSoda, WaterField};
                Item items = new Item(Jarr);
                if (!items.Transform()) {
                        JOptionPane.showMessageDialog(this, "Cannot read inputs");
                } else {
                        FieldRes.setText(items.toString());
                }

        }

        private void BtnClearActionPerformed(java.awt.event.ActionEvent evt) {
                FieldRes.setText("0");
                JTextField[] Jarr = new JTextField[]{FieldDog, FieldBrat, FieldHam, FieldFries, FieldSoda, WaterField};
                for (int i = 0; i < Jarr.length; i++){
                        Jarr[i].setText("0");
                }
        }

        private void ButtonExitActionPerformed(java.awt.event.ActionEvent evt) {
                // TODO add your handling code here:
                System.exit(0);
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> {
                        new RunnerFrame().setVisible(true);
                });
        }

}
